
export type CarouselItemInterface = {
  /**
    * @param name - The first input number
    * @param image - The second input number
    */
  name: string;
  image: string;
}

export type Supply = {
  /**
   * @param id - document unique id, autogenerated
   * @param name - supply namme
   * @param unit - unit of measurement use
   * @param amount - the amount of supply
   * @param updatedAt - should be serverTimestamp from firebase
   */
  id?: string;
  name: string;
  unit: string;
  amount: number;
};

export type Variant = {
  name: string,
  price: number
}
export type Product = {
  name: string,
  description: string,
  image: string,
  variants: Variant[]
}
// export type KeyStringValNum = { [key: string]: number }

type CartItemVariant = Variant & {
  subTotal: number
}

export type CartItem = {
  name: string
  quantity: number
  price: number
  subTotal: number
  image: string
}

export type ContactInfo = {
  firstName: string;
  lastName: string;
  phoneNumber: string;
};

export type Address = {
  id?: string
  street_line1: string;
  street_line2: string;
  city: string;
  state: string;
  postal_code: string;
  country: string;
};

export type CityOption = {
  name: string;
  city: string;
  state: string;
  postal_code: string;
};