
export type CarouselItemInterface = {
  /**
    * @param name - The first input number
    * @param image - The second input number
    */
  name: string;
  image: string;
}

export type Supply = {
  /**
   * @param id - document unique id, autogenerated
   * @param name - supply namme
   * @param unit - unit of measurement use
   * @param amount - the amount of supply
   * @param updatedAt - should be serverTimestamp from firebase
   */
  id?: string;
  name: string;
  unit: string;
  amount: number;
};